spring.datasource.url=jdbc:mysql://localhost:3306/pharmali
spring.datasource.username=root
spring.datasource.password=Jaki123...
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8080
spring.thymeleaf.enabled=false
spring.mvc.static-path-pattern=/static/**
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false
spring.jackson.deserialization.ACCEPT_SINGLE_VALUE_AS_ARRAY=true
spring.resources.static-locations=file:./uploads/






spring.thymeleaf.check-template-location=false


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=FCB15DFC82DBB
spring.mail.password=06ee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
